global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'conveyor-belt'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:5000']
        labels:
          service: 'production-line'
          environment: 'production'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          role: 'node-metrics'